[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "12.1.0-beta"

[[constraint]]
  branch = "master"
  name = "github.com/rubiojr/go-vhd"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true